In [ ]:
import scipy.optimize as spyopt
import numpy as np
import matplotlib.pyplot as plt
import time

In [ ]:
class report:
    def __init__(self,initial_guess):
        self.initial_guess = initial_guess
        self.store = initial_guess
        
    def reporter(self,p):
        self.store = np.vstack((self.store, p))
    
    def check_lim(self):
        xlim = np.array([self.initial_guess[0],self.initial_guess[0]])
        for coord in self.store:
            if xlim[0] > coord[0]:
                xlim[0] = coord[0]
            if xlim[1] < coord[0]:
                xlim[1] = coord[0]
        self.xlim = xlim   
        
        ylim = np.array([self.initial_guess[1],self.initial_guess[1]])
        for coord in self.store:
            if ylim[0] > coord[1]:
                ylim[0] = coord[1]
            if ylim[1] < coord[1]:
                ylim[1] = coord[1]
        self.ylim = ylim  

In [ ]:
inital_guess = np.array([-1,1])
my_report = report(inital_guess)
NM = spyopt.minimize(spyopt.rosen,inital_guess,method="Powell",  callback=my_report.reporter)

In [ ]:
my_report.check_lim()

In [ ]:
fig, ax = plt.subplots(dpi=100)
xsize = abs(my_report.xlim[0] - my_report.xlim[1])
ysize = abs(my_report.ylim[0] - my_report.ylim[1])
x = np.linspace(my_report.xlim[0]-xsize/4,my_report.xlim[1]+xsize/4,2001)
y = np.linspace(my_report.ylim[0]-ysize/4,my_report.ylim[1]+ysize/4,2001)
x_coord, y_coord = np.meshgrid(x,y)
f = lambda x,y: spyopt.rosen([x, y])
z_coord = f(x_coord,y_coord)
ax.contour(x_coord,y_coord, z_coord, np.arange(12)**5)

ax.plot(my_report.store[:, 0], my_report.store[:, 1], '-o')
ax.plot(NM["x"][0], NM["x"][1],"x")

In [ ]:
my_report.store

In [ ]:
def timer(func):
    def time_check(*args,**kwargs):
        start_time = time.perf_counter()
        result = func(*args, **kwargs)
        hours, rem = divmod(time.perf_counter()-start_time, 3600)
        minutes, seconds = divmod(rem, 60)
        print("Time taken for code execution: {:0>2}:{:0>2}:{:02.0f} (HH:MM:SS)".format(int(hours),int(minutes),seconds))
        return result
    return time_check

In [ ]:
@timer
def wait(x):
    time.sleep(x)
    return 1,2
    

In [ ]:
x,y = wait(1)
print(x)
print(y)

In [7]:
import numpy as np
import numpy.random as rand

In [8]:
rng = rand.default_rng()
vals = rng.standard_normal(10)

In [9]:
vals

array([-0.7856385 , -0.93291497,  0.18216735,  1.0972542 , -1.62228421,
        1.53270336,  0.88971426, -0.71708333, -1.89174251, -0.4230328 ])

In [12]:
sample = rng.choice(10,5,replace=False)
sample_other = np.delete(np.arange(10),sample)
print(sample)
print(sample_other)

[4 0 3 2 9]
[1 5 6 7 8]


In [14]:
x = np.array([232,6436,342,64369,945,4564,74,68,5,67482])
len(x)

10

In [15]:
x[sample]

array([  945,   232, 64369,   342, 67482])